version: '3.8'

services:
  node0:
    build: .
    environment:
      - NODE_ID=0
      - NODE_PORT=8080
      - DOCKER_MODE=true
    ports:
      - "8080:8080"
    networks:
      - quorum-net
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  node1:
    build: .
    environment:
      - NODE_ID=1
      - NODE_PORT=8080
      - DOCKER_MODE=true
    ports:
      - "8081:8080"
    networks:
      - quorum-net
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  node2:
    build: .
    environment:
      - NODE_ID=2
      - NODE_PORT=8080
      - DOCKER_MODE=true
    ports:
      - "8082:8080"
    networks:
      - quorum-net
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  node3:
    build: .
    environment:
      - NODE_ID=3
      - NODE_PORT=8080
      - DOCKER_MODE=true
    ports:
      - "8083:8080"
    networks:
      - quorum-net
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  node4:
    build: .
    environment:
      - NODE_ID=4
      - NODE_PORT=8080
      - DOCKER_MODE=true
    ports:
      - "8084:8080"
    networks:
      - quorum-net
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    image: python:3.9-slim
    command: python3 -m http.server 8090
    working_dir: /app/web
    ports:
      - "8090:8090"
    volumes:
      - ./web:/app/web
    networks:
      - quorum-net

networks:
  quorum-net:
    driver: bridge
