#!/bin/bash
echo ""
echo "  ┌─────────────────────────────────────────────────────────┐"
echo "  │   Service Mesh Sidecar Latency Demo                     │"
echo "  │   Article 207 — System Design Interview Roadmap         │"
echo "  └─────────────────────────────────────────────────────────┘"
echo ""
echo "  Dashboard:          http://localhost:5000"
echo "  Load Generator:     http://localhost:4000/metrics"
echo "  Envoy A Admin:      http://localhost:9901"
echo "  Envoy B Admin:      http://localhost:9902"
echo ""
echo "  To change RPS:  edit RPS env var in docker-compose.yml and restart"
echo "                  docker compose up -d --scale load-generator=1"
echo ""
echo "  What to watch:"
echo "  • p99 latency climbs when filter chain processing spikes"
echo "  • Envoy admin /stats shows connection pool utilization"
echo "  • /api/chain calls show two-hop sidecar cost"
echo ""
