version: '3.8'

services:
  # Load balancer
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ../../nginx/configs/blue-green.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_blue_1
      - app_blue_2
      - app_blue_3
      - app_green_1
      - app_green_2
      - app_green_3
    networks:
      - app_network

  # Blue environment (v1)
  app_blue_1:
    build: ../../app/v1
    environment:
      - INSTANCE_ID=blue-instance-1
      - PORT=5000
    networks:
      - app_network

  app_blue_2:
    build: ../../app/v1
    environment:
      - INSTANCE_ID=blue-instance-2
      - PORT=5000
    networks:
      - app_network

  app_blue_3:
    build: ../../app/v1
    environment:
      - INSTANCE_ID=blue-instance-3
      - PORT=5000
    networks:
      - app_network

  # Green environment (v2)
  app_green_1:
    build: ../../app/v2
    environment:
      - INSTANCE_ID=green-instance-1
      - PORT=5000
    networks:
      - app_network

  app_green_2:
    build: ../../app/v2
    environment:
      - INSTANCE_ID=green-instance-2
      - PORT=5000
    networks:
      - app_network

  app_green_3:
    build: ../../app/v2
    environment:
      - INSTANCE_ID=green-instance-3
      - PORT=5000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
