
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  hot-partition-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - .:/app
    command: ["python", "-m", "uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  partition-simulator:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - .:/app
    command: ["python", "src/core/simulator.py"]

volumes:
  redis_data:
