#!/bin/bash
echo "======================================================"
echo " RAG Pipeline Demo"
echo "======================================================"
echo ""
echo " Dashboard : http://localhost:3000"
echo " API       : http://localhost:8000"
echo " API Docs  : http://localhost:8000/docs"
echo ""
echo " Sample queries to try:"
echo "  - how does consistent hashing work?"
echo "  - what causes split-brain?"
echo "  - explain bloom filters"
echo "  - what is backpressure?"
echo ""
echo " Press Ctrl+C to exit demo (containers keep running)"
echo "======================================================"
