version: '3.8'

services:
  consistent-hash-demo:
    build: .
    ports:
      - "5000:5000"
      - "6379:6379"
    volumes:
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://localhost:6379

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
