version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - redundancy-net

  lb:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - LOAD_BALANCER=true
    depends_on:
      - service1
      - service2
      - service3
      - service4
    networks:
      - redundancy-net
    restart: unless-stopped

  service1:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - SERVICE_PORT=3001
      - SERVICE_ID=service-1
      - SERVICE_REGION=us-east-1
    networks:
      - redundancy-net
    restart: unless-stopped

  service2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - SERVICE_PORT=3002
      - SERVICE_ID=service-2
      - SERVICE_REGION=us-east-1
    networks:
      - redundancy-net
    restart: unless-stopped

  service3:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - SERVICE_PORT=3003
      - SERVICE_ID=service-3
      - SERVICE_REGION=us-west-2
    networks:
      - redundancy-net
    restart: unless-stopped

  service4:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - SERVICE_PORT=3004
      - SERVICE_ID=service-4
      - SERVICE_REGION=eu-west-1
    networks:
      - redundancy-net
    restart: unless-stopped

networks:
  redundancy-net:
    driver: bridge
