apiVersion: 1
datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: false
    jsonData:
      maxLines: 1000
      timeout: 60

  - name: Elasticsearch
    type: elasticsearch
    uid: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "logs-*"
    version: 1
    editable: false
    jsonData:
      esVersion: "8.x"
      timeField: "@timestamp"
      interval: Daily
      logMessageField: message
      logLevelField: level
