global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8001']
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8002']
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8003']
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'security-monitor'
    static_configs:
      - targets: ['security-monitor:8080']
