#!/bin/bash
echo "🎯 RTB System Demo"
echo "=================="
echo ""
echo "📊 Dashboard: http://localhost:3000"
echo "📡 Exchange API: http://localhost:3001"
echo ""
echo "Services running:"
echo "  • Ad Exchange (simulating auctions every 500ms)"
echo "  • FastBidder (cached strategy, ~10ms latency)"
echo "  • SmartBidder (ML strategy, ~40ms latency)"
echo "  • AggressiveBidder (minimal processing, ~5ms latency)"
echo ""
echo "Watch the dashboard to see:"
echo "  • Real-time auction results"
echo "  • Latency percentiles (P50, P95, P99)"
echo "  • Bidder competition and timeouts"
echo ""
echo "Press Ctrl+C to stop watching logs..."
docker-compose logs -f
