version: '3.8'

services:
  # Load balancer
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../../nginx/configs/rolling.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_v1_1
      - app_v1_2
      - app_v1_3
    networks:
      - app_network

  # App instances v1
  app_v1_1:
    build: ../../app/v1
    environment:
      - INSTANCE_ID=v1-instance-1
      - PORT=5000
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  app_v1_2:
    build: ../../app/v1
    environment:
      - INSTANCE_ID=v1-instance-2
      - PORT=5000
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  app_v1_3:
    build: ../../app/v1
    environment:
      - INSTANCE_ID=v1-instance-3
      - PORT=5000
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app_network:
    driver: bridge
