
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./templates:/app/templates

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  load-generator:
    build: .
    command: python tests/load_generator.py
    depends_on:
      - app
    environment:
      - TARGET_URL=http://app:8080
