#!/bin/bash

echo "🎬 Starting Future System Design Patterns Demo..."
echo ""
echo "Dashboard: http://localhost:8080"
echo ""
echo "Services:"
echo "  • AI Router:          http://localhost:3001"
echo "  • Metrics Collector:  http://localhost:3003"
echo ""
echo "Try these commands:"
echo "  1. Send a request:"
echo "     curl -X POST http://localhost:3001/route \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"type\":\"compute\",\"priority\":\"high\",\"userRegion\":\"us-west\"}'"
echo ""
echo "  2. View router stats:"
echo "     curl http://localhost:3001/stats"
echo ""
echo "  3. View metrics:"
echo "     curl http://localhost:3003/metrics"
echo ""
echo "Press Ctrl+C to stop watching logs..."
echo ""
docker-compose logs -f
