#!/bin/bash
echo "=== Feature Flag System Demo ==="
echo ""
echo "Dashboard: http://localhost:8080"
echo ""
echo "Try these commands:"
echo ""
echo "# Check flag service stats"
echo "curl http://localhost:3000/stats"
echo ""
echo "# Evaluate flag for a user"
echo "curl -X POST http://localhost:3000/evaluate \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"flagId\":\"new-payment-flow\",\"userId\":\"user-123\",\"context\":{}}'"
echo ""
echo "# Test checkout service"
echo "curl http://localhost:3001/checkout/user-456"
echo ""
echo "# Test payment service"
echo "curl http://localhost:3002/process/user-789"
echo ""
echo "# Test recommendations service"
echo "curl http://localhost:3003/recommendations/user-101"
echo ""
echo "Services are running. Press Ctrl+C to stop."
docker-compose logs -f
