version: '3.8'

services:
  # Load balancer
  nginx:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ../../nginx/configs/canary.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_stable_1
      - app_stable_2
      - app_stable_3
      - app_canary_1
    networks:
      - app_network

  # Stable environment (v1)
  app_stable_1:
    build: ../../app/v1
    environment:
      - INSTANCE_ID=stable-instance-1
      - PORT=5000
    networks:
      - app_network

  app_stable_2:
    build: ../../app/v1
    environment:
      - INSTANCE_ID=stable-instance-2
      - PORT=5000
    networks:
      - app_network

  app_stable_3:
    build: ../../app/v1
    environment:
      - INSTANCE_ID=stable-instance-3
      - PORT=5000
    networks:
      - app_network

  # Canary environment (v2)
  app_canary_1:
    build: ../../app/v2
    environment:
      - INSTANCE_ID=canary-instance-1
      - PORT=5000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
