
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  stateless-service:
    build: .
    command: python -m uvicorn src.stateless.service:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - SERVICE_TYPE=stateless
      - REDIS_URL=redis://redis:6379

  stateful-service:
    build: .
    command: python -m uvicorn src.stateful.service:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - SERVICE_TYPE=stateful
      - REDIS_URL=redis://redis:6379

  dashboard:
    build: .
    command: python src/dashboard.py
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  load-tester:
    build: .
    command: python src/load_tester.py
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      - stateless-service
      - stateful-service
    profiles:
      - testing

volumes:
  redis_data:
