version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - REDIS_URL=redis://redis:6379
      - GATEWAY_URL=http://gateway:3001
      - NODE_ENV=production
    depends_on:
      - redis
      - gateway
    volumes:
      - ./logs:/app/logs

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_GATEWAY_URL=ws://localhost:3001
      - REACT_APP_API_URL=http://localhost:3002
    depends_on:
      - gateway
      - notification-service

  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    environment:
      - GATEWAY_URL=ws://gateway:3001
      - API_URL=http://notification-service:3002
    depends_on:
      - gateway
      - notification-service
    profiles:
      - test

volumes:
  redis_data:
