version: '3.8'

services:
  gossip-demo:
    build: .
    ports:
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
      - "9004:9004"
      - "9005:9005"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    network_mode: host
