global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway-service:8000']
    metrics_path: '/metrics'
  
  - job_name: 'backend'
    static_configs:
      - targets: ['backend-service:8001']
    metrics_path: '/metrics'
