version: '3.8'
services:
  circuit-breaker:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - TERM=xterm-256color
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s