#!/bin/bash
echo ""
echo "  Noisy Neighbor Demo"
echo "  ─────────────────────────────────────────"
echo ""
echo "  Dashboard:   http://localhost:3001"
echo "  Metrics API: http://localhost:3001/metrics"
echo "  Health:      http://localhost:3001/health"
echo ""
echo "  Tenant tiers:"
echo "    tenant-free        10 req/s  burst: 20   (noisy neighbor)"
echo "    tenant-pro        100 req/s  burst: 200"
echo "    tenant-enterprise 500 req/s  burst: 1000"
echo ""
echo "  Load generator sends:"
echo "    FREE:  30 req/s (3× over limit → heavy throttle)"
echo "    PRO:  120 req/s (1.2× over limit → occasional throttle)"
echo "    ENT:  300 req/s (0.6× limit → always allowed)"
echo ""
echo "  Try manual requests:"
echo "    curl http://localhost:3001/api/data?tenant=tenant-free"
echo "    curl http://localhost:3001/api/data?tenant=tenant-pro"
echo "    curl http://localhost:3001/api/data?tenant=tenant-enterprise"
echo ""
echo "  Run cleanup:  bash cleanup.sh"
echo ""
