global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'coordinator'
    static_configs:
      - targets: ['coordinator:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'shipping-service'
    static_configs:
      - targets: ['shipping-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
