version: '3.8'

services:
  # Primary Database
  postgres-primary:
    image: postgres:16
    environment:
      POSTGRES_DB: scaling_demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres 
      -c wal_level=replica 
      -c max_wal_senders=3 
      -c max_replication_slots=3
      -c hot_standby=on
      -c archive_mode=on
      -c archive_command='cp %p /var/lib/postgresql/archive/%f'
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      - postgres_archive:/var/lib/postgresql/archive
    ports:
      - "5432:5432"
    networks:
      - db_network

  # Read Replica 1
  postgres-replica1:
    image: postgres:16
    environment:
      POSTGRES_DB: scaling_demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      PGUSER: demo_user
    command: |
      bash -c "
      until pg_basebackup -h postgres-primary -D /var/lib/postgresql/data -U demo_user -v -P -W -R; do
        echo 'Waiting for primary to be ready...'
        sleep 5
      done
      postgres"
    volumes:
      - postgres_replica1_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      - postgres-primary
    networks:
      - db_network

  # Read Replica 2  
  postgres-replica2:
    image: postgres:16
    environment:
      POSTGRES_DB: scaling_demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      PGUSER: demo_user
    command: |
      bash -c "
      until pg_basebackup -h postgres-primary -D /var/lib/postgresql/data -U demo_user -v -P -W -R; do
        echo 'Waiting for primary to be ready...'
        sleep 5
      done
      postgres"
    volumes:
      - postgres_replica2_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    depends_on:
      - postgres-primary
    networks:
      - db_network

  # Shard 1 (US Region)
  postgres-shard-us:
    image: postgres:16
    environment:
      POSTGRES_DB: scaling_demo_us
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    volumes:
      - postgres_shard_us_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - db_network

  # Shard 2 (EU Region)
  postgres-shard-eu:
    image: postgres:16
    environment:
      POSTGRES_DB: scaling_demo_eu
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    volumes:
      - postgres_shard_eu_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - db_network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - db_network

  # Application
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-primary
      - postgres-replica1
      - postgres-replica2
      - postgres-shard-us
      - postgres-shard-eu
      - redis
    environment:
      - DATABASE_PRIMARY_URL=postgresql://demo_user:demo_pass@postgres-primary:5432/scaling_demo
      - DATABASE_REPLICA1_URL=postgresql://demo_user:demo_pass@postgres-replica1:5432/scaling_demo
      - DATABASE_REPLICA2_URL=postgresql://demo_user:demo_pass@postgres-replica2:5432/scaling_demo
      - DATABASE_SHARD_US_URL=postgresql://demo_user:demo_pass@postgres-shard-us:5432/scaling_demo_us
      - DATABASE_SHARD_EU_URL=postgresql://demo_user:demo_pass@postgres-shard-eu:5432/scaling_demo_eu
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./templates:/app/templates
    networks:
      - db_network

volumes:
  postgres_primary_data:
  postgres_replica1_data:
  postgres_replica2_data:
  postgres_shard_us_data:
  postgres_shard_eu_data:
  postgres_archive:

networks:
  db_network:
    driver: bridge
