version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  rate-limiter-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - APP_ENV=development
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
      - ./static:/app/static
      - ./logs:/app/logs

  load-tester:
    build: .
    command: python tests/load_test.py
    environment:
      - TARGET_URL=http://rate-limiter-app:8000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - rate-limiter-app
    profiles:
      - testing

volumes:
  redis_data:
