#!/bin/bash

echo "🎬 Event Sourcing & CQRS Demo"
echo "=============================="
echo ""
echo "1. Open dashboard: http://localhost:3000"
echo ""
echo "2. Try these scenarios:"
echo "   - Create accounts with different IDs"
echo "   - Make deposits and withdrawals"
echo "   - Watch events appear in real-time"
echo "   - Notice the projection lag (100ms delay)"
echo "   - Try the replay button to rebuild projections"
echo ""
echo "3. Services:"
echo "   Command Service:    http://localhost:3002"
echo "   Query Service:      http://localhost:3003"
echo "   Event Store:        http://localhost:3001"
echo "   Projection Stats:   http://localhost:3004/stats"
echo ""
echo "4. Observe eventual consistency:"
echo "   - Make a deposit"
echo "   - Immediately query the account"
echo "   - Notice the brief delay before balance updates"
echo ""
echo "Press Ctrl+C to stop watching logs..."
echo ""

docker-compose logs -f
