version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  order-service:
    build: ./order-context
    ports:
      - "8001:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=order-service
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./shared:/app/shared

  inventory-service:
    build: ./inventory-context
    ports:
      - "8002:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=inventory-service
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./shared:/app/shared

  shipping-service:
    build: ./shipping-context
    ports:
      - "8003:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=shipping-service
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./shared:/app/shared

  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_ORDER_API=http://localhost:8001
      - REACT_APP_INVENTORY_API=http://localhost:8002
      - REACT_APP_SHIPPING_API=http://localhost:8003
    depends_on:
      - order-service
      - inventory-service
      - shipping-service

