version: '3.8'

services:
  auth-service:
    build: .
    command: python src/services/auth_service.py
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  user-service:
    build: .
    command: python src/services/user_service.py
    ports:
      - "8002:8002"
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - auth-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  order-service:
    build: .
    command: python src/services/order_service.py
    ports:
      - "8003:8003"
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - user-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  dashboard:
    build: .
    command: python src/web/dashboard.py
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - auth-service
      - user-service
      - order-service
