version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: failover-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  app:
    build: .
    container_name: failover-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - REGION=us-east-1
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
      - ./web:/app/web
    restart: unless-stopped

volumes:
  redis_data:
