version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: notification-redis
    ports:
      - "6379:6379"
    networks:
      - notif-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: notification-app
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - notif-network
    environment:
      - NODE_ENV=production

networks:
  notif-network:
    driver: bridge
