version: '3.8'

services:
  raft-cluster:
    build: .
    ports:
      - "8001-8005:8001-8005"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: python cluster.py 5

  # Individual node services for advanced testing
  node1:
    build: .
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    command: python node.py node1 8001 8001,8002,8003,8004,8005
    profiles: ["individual"]

  node2:
    build: .
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
    command: python node.py node2 8002 8001,8002,8003,8004,8005
    profiles: ["individual"]

  node3:
    build: .
    ports:
      - "8003:8003"
    environment:
      - PYTHONUNBUFFERED=1
    command: python node.py node3 8003 8001,8002,8003,8004,8005
    profiles: ["individual"]

  node4:
    build: .
    ports:
      - "8004:8004"
    environment:
      - PYTHONUNBUFFERED=1
    command: python node.py node4 8004 8001,8002,8003,8004,8005
    profiles: ["individual"]

  node5:
    build: .
    ports:
      - "8005:8005"
    environment:
      - PYTHONUNBUFFERED=1
    command: python node.py node5 8005 8001,8002,8003,8004,8005
    profiles: ["individual"]
